stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreInstaller@2
      displayName: 'Use .NET Core sdk 3.0.100-preview3-010431'
      inputs:
        version: '3.0.100-preview3-010431'
        performMultiLevelLookup: true
    - task: PowerShell@2
      displayName: 'Nuke build'
      inputs:
        targetType: filePath
        filePath: ./build.ps1
        arguments: 'Pack Coverage --CoberturaReport'
      env:
        NugetToken: $(nuget_token)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/Artifacts'
        ArtifactName: 'artifacts'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/TestResults'
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/coverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/coverage'
- stage: Deploy
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    environment: 'nuget'
    steps:
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          downloadPath: '$(System.DefaultWorkingDirectory)/artifacts'
          artifactName: 'artifacts'
      - task: PowerShell@2
        displayName: 'Nuke build'
        inputs:
          targetType: filePath
          filePath: ./build.ps1
          arguments: 'Push -ApiKey $env:NugetToken -ArtifactsDirectory $(System.DefaultWorkingDirectory)/artifacts'
        env:
          NugetToken: $(nuget_token)
schedules:
- cron: "0 0 * * *"
  displayName: nightly
  branches:
    include:
    - master
  always: false
